export { MdLocationOn as Location } from "react-icons/md";
export { MdOutlineFormatListBulleted as Menu } from "react-icons/md";
export { MdSearch as Search } from "react-icons/md";
export { MdAccountCircle as AccountCircle } from "react-icons/md";
export { MdStar as Star } from "react-icons/md";
export { MdShoppingCart as Shopping } from "react-icons/md";
export { MdDone as Done } from "react-icons/md";
export { MdKeyboardArrowRight as Next } from "react-icons/md";
export { MdKeyboardArrowLeft as Previous } from "react-icons/md";
